name: unleash
description: A dart client for Unleash. Unleash is a simple and easy to use feature toggle (feature flag) service.
version: 0.3.0
homepage: https://github.com/valksandro/unleash2
repository: https://github.com/valksandro/unleash2
issue_tracker: https://github.com/valksandro/unleash2/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  http: ^0.13.0
  path: ^1.8.0

dev_dependencies:
  coverage: ^1.0.2
  test: ^1.16.0
  yaml: ^3.0.0
